baseURL: https://brabalawuka.cc/
languageCode: en-us
title: Brabalawuka's Blog
description: Blog Site of Brabalawuka, trying to be an interesing developer. Sharing learnings and thoughts~
paginate: 10
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
googleAnalytics: G-65QJ8P8DW0

services:
  googleAnalytics:
    ID: G-65QJ8P8DW0
minify:
    disableXML: true
    # minifyOutput: true

menu:
    main:
        # - name: Home 
        #   url: /
        #   weight: 1
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 4
        - name: Tags
          url: tags/
          weight: 3
        - name: Categories
          url: categories/
          weight: 2
        - name: About
          url: about/
          weight: 6

params:
    # defaultTheme: light
    # defaultTheme: dark
    defaultTheme: auto # to switch between dark or light according to browser theme
    assets:
        disableFingerprinting: true

    homeInfoParams:
        Title: "Brabalawuka'Blog"
        Content: >
            让生活有趣一点~  

            分享一些感悟，心得，学习笔记~  

            Sharing random thoughts~


    socialIcons:
        - name: Twitter
          url: "https://twitter.com/brabalawuka"
        - name: LinkedIn
          url: "https://www.linkedin.com/in/zizheng-lyu-84404912a/"
        - name: Instagram
          url: "https://www.instagram.com/brabalawuka"
        - name: github
          url: "https://github.com/Brabalawuka"

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

    cover:
        responsiveImages: true
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page
    customRSSFeeds:
      - name: "Brabalawuka's Blog"
        url: "https://brabalawuka.cc/index.xml"
        description: "Blog Site of Brabalawuka, trying to be an interesing developer. Sharing learnings and thoughts~"
        feed_id: "5255442307418297+userId:66026363247791104"


  
    ShowShareButtons: true
    ShowReadingTime: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    ShowBreadCrumbs: false
    comments: true
    images: ["cover.JPEG", "avatar.JPG"]


    Instagram:
      appId: "863441064943702"
      clientToken: "2613058ab9efc1001bd60634a1abae14"



outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

taxonomies:
    category: categories
    tag: tags
    series: series