/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 733b6e887ca86b5a4f64c3a590a61a46)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
